### ISSUE TITLE
undefined method undefined local variable or method `puma_socket' for SSHKit::Backend::Netssh

### ISSUE THREAD

**Issue by radar** [xijo/capistrano-puma#4]
With my application here: https://github.com/radar/nf_performance_spree, (checkout to 2def4a0e0dfaa2bfce7003572cbec1a61336bd83) when I attempt to run `cap production puma:start`, I receive this error:

```
cap aborted!
undefined local variable or method `puma_socket' for #<SSHKit::Backend::Netssh:0x007fe6d3124dc0>
/Users/ryanbigg/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/capistrano-puma-0.2.1/lib/capistrano/tasks/puma.rake:9:in `block (5 levels) in <top (required)>'
/Users/ryanbigg/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sshkit-1.2.0/lib/sshkit/backends/abstract.rb:89:in `with'
/Users/ryanbigg/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/capistrano-puma-0.2.1/lib/capistrano/tasks/puma.rake:8:in `block (4 levels) in <top (required)>'
/Users/ryanbigg/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sshkit-1.2.0/lib/sshkit/backends/abstract.rb:81:in `within'
/Users/ryanbigg/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/capistrano-puma-0.2.1/lib/capistrano/tasks/puma.rake:7:in `block (3 levels) in <top (required)>'
/Users/ryanbigg/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sshkit-1.2.0/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/ryanbigg/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sshkit-1.2.0/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/ryanbigg/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/sshkit-1.2.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
```

I don't know what could be possibly causing this, but it appears to be coming from the internals of capistrano-puma.

I am switching to using pumactl for the time being.

**Comment by tobidelius** [comment]
Same here

**Comment by radar** [comment]
I was able to fix this in the app by replacing the variable calls with fetch calls:

fetch(:puma_socket)

**Comment by radar** [comment]
@sandelius Could you please try out my fork and let me know if that fixes the problem for you?

**Comment by masterkain** [comment]
I have this on any puma command:

```
undefined local variable or method `puma_state' for #<SSHKit::Backend::Netssh:0x007fdc80df5a48>
/Users/kain/.rvm/gems/ruby-2.1.0-preview2@myapp/bundler/gems/capistrano-puma-f538bcb7c1dc/lib/capistrano/tasks/puma.rake:42:in `block (4 levels) in <top (required)>'
/Users/kain/.rvm/gems/ruby-2.1.0-preview2@myapp/gems/sshkit-1.2.0/lib/sshkit/backends/abstract.rb:81:in `within'
/Users/kain/.rvm/gems/ruby-2.1.0-preview2@myapp/bundler/gems/capistrano-puma-f538bcb7c1dc/lib/capistrano/tasks/puma.rake:41:in `block (3 levels) in <top (required)>'
/Users/kain/.rvm/gems/ruby-2.1.0-preview2@myapp/gems/sshkit-1.2.0/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/kain/.rvm/gems/ruby-2.1.0-preview2@myapp/gems/sshkit-1.2.0/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/kain/.rvm/gems/ruby-2.1.0-preview2@myapp/gems/sshkit-1.2.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
```

using `master`.
